name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
        build_type: [Debug, Release]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3



      - name: Configure CMake
        run: cmake -S . -B build -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}

      - name: Build project
        run: cmake --build build --config ${{ matrix.build_type }}

      - name: Run tests
        run: ctest -C ${{ matrix.build_type }} --output-on-failure
